// AUTO-GENERATED by scripts/build-images.mjs — do not edit by hand.
export type ImageAsset = { widths: number[]; ratio: number; lqip: string };
export const IMAGES = {
  "hero-ocean": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2400
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABQAwCdASoWAAwAPuloq06pJiQiMAgBIB0JYwCdAA/boQyI+AD+gNMmn7w36F5YPgNSEYPHiJMAN2KgZL3nEcmZjmCl4yaTWFa6vV2aPgAAAA=="
  },
  "ocean-texture": {
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoWAAwAPulep00pJSOiMAgBIB0JYwCdACFrfZqJbDMVoh5hAAD94lm2/nB3jzU9Cwh+4/DeJvmdq1SCkgiOISUnuJ+WAAAA"
  },
  "suite-ocean": {
    "widths": [
      480,
      768,
      1200,
      1400
    ],
    "ratio": 0.8,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBQCdASoWABwAPulkqU2pJaQiMAgBIB0JZwC7M2QC++nTpZ+b+HUsX0aG1Kz7gWevsvIAAP7s+uoPD+jWh6VMSBZKsgA7IdAVFDclp89ncQ7gqOWWnx3+CVf6rfRm4hIsseXrh477LPI2ZXIKPXELqIiNY+QAvHbMi49sDFQ+T/q9FOAgAAAA"
  },
  "suite-panorama": {
    "widths": [
      480,
      768,
      1200,
      1400
    ],
    "ratio": 0.8,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBQCdASoWABwAPuleqk8pJKOiMBgIASAdCUATpmHQo//QBHWAxIP/z4u5LiZiCbiAAP7sVcxbu/7g9M4KtB8L9XQcMeeeEw5602UuCBQfMURjtOXeV2ajZ2mVEJbT4mOsGTL6jZfQDl008PQZ1tKCPipBm4WqAfasC4sH/ybMtFX3kntj2xYdR5jWdSC3R+GgQo5WAOVJSAsSigAAAA=="
  },
  "suite-grand": {
    "widths": [
      480,
      768,
      1200,
      1400
    ],
    "ratio": 0.8,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoWABwAPt1gpk0opiOiMAwBEBuJZQAAW8sDz8tz/3fGYcZ/oBjbG6E6yoAA/naGZAa8tIAUU7SrcvYy8f+3ft9kh7gDni4PAJBABK/LiaeALa+fk8d9SXwT4U5X5eW6xuxeeVnyAPKOvNAv7VVDsAAA"
  },
  "suite-residence": {
    "widths": [
      480,
      768,
      1200,
      1400
    ],
    "ratio": 0.8,
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwBACdASoWABwAPulosE+pJiUiKAqpIB0JZQCsABEc6tbmPDz4prjrDRFebnnIbHgA/u7uKyp86/zrEretiP/MdFg1qi7Lth2FCChmI/+quIjHjdV2qwJw6hkb1DCSy2JwKc57UWdxjAAA"
  },
  "featured-suite": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2200
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoWAAwAPulgqU0pJaQiMAgBIB0JZQCdAB9S4+3JhE56JBgAAP1Qix8Ku4R4FGvhPRWh4c0k0a9U7mjJiLLdLIqGA421MAAA"
  },
  "detail-view": {
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "ratio": 1.5,
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoWAA8APulmq00pJiQiMAgBIB0JZQB3AAPbOvcSzjTaZXZgAM40292hgo6+qralS40J4HhRPhO2GI7rDwTx8/ZcKF1Ygi2StRvhNAHPDGzg4vFbKVzwggALf+8B1RR87DCq4gAA"
  },
  "detail-space": {
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "ratio": 1.5,
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoWAA8APulgqE0pJaQiMAgBIB0JQBOmUABpkRknPPsO3rzxIAD+0fB2khi9xv1aG9mv0PmS1IoMXHyBgBAS4W5wmF2mzxM9fjpsk6+fMxNAplEcU3FDGOmCXwAAAA=="
  },
  "detail-details": {
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "ratio": 1.5,
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwBACdASoWAA8APulgqk2pJaQiMAgBIB0JZwDGfCPfBegXUuxm3ads+gAAytO7Yju6GJgtZLyufGkN7pZEDLiaZ0gVMKe2DV/c3YZw5+NnHpzOwKLMEAAA"
  },
  "detail-service": {
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "ratio": 1.5,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoWAA8APulgqU0pJaQiMAgBIB0JYwC7ACB9mIyzKcJJUAD+1LPHMAyZ6V65hL/quXORnWWfjSE68GU6MNxNbmbuZhSszMeUiyDZYFrvq7yDPpTDqr5jdXgAAAA="
  },
  "dest-santorini": {
    "widths": [
      480,
      768,
      1200
    ],
    "ratio": 0.75,
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBQCdASoWAB0APulipU2pJaMiMBgMASAdCUAToAIdiYS9uEXW0tPq/qX/aX5wX84AgAD+vHExM7s3/cNN+EMlO9dtTw1rYe9TSK/Wi9SWshMYgz2KWcZQTpkX//Mh+U7ly39Qqq35CAJK513FUHNB4fAI+NasKcz31/ZMR27Kf8jTkq/YSJrAAAA="
  },
  "dest-maldives": {
    "widths": [
      480,
      768,
      1200
    ],
    "ratio": 0.75,
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoWAB0APuVcqk0pJSQiMBgMASAciUAXYAIdmxGUh5CGDnMjDoAA8LaHl7as8s3kysEThytC0nYXWTi4w8iofbbWCFdUAXVhl2QU4f2wJOQCFiSw9JLw+rOdFl5gRLwH3PhebrR+hbF7xYgAAAA="
  },
  "dest-dubai": {
    "widths": [
      480,
      768,
      1200
    ],
    "ratio": 0.75,
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBQCdASoWAB0APtlUpE0oJKOiN/qoAQAbCUAYUAQ9+FDndHJV4quNthbkCKiLmAwAAP0vQ2mKeyPSvUuEcuDLbYqPLM4V168rEgnrGGZrVk6H/430lKfzaCvGSx613v1mqQ5RsRY0AAAA"
  },
  "dest-mediterranean": {
    "widths": [
      480,
      768,
      1200
    ],
    "ratio": 0.75,
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoWAB0APs1SoE0npKMiN+gA8BmJZACdADJC2TLdiNQb/EV2cWoRPdYAAP64yjkBXNHryOd4D3KfX3lC0XxaxHQo8QL2HLBmB83vdxA0c3L3XjVnpNFIo66cMJXb7kEqccR26K+uNfFVHQ8+iJRfpr+0qk+gAA=="
  },
  "dest-fjords": {
    "widths": [
      480,
      768,
      1200
    ],
    "ratio": 0.75,
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBQCdASoWAB0APtVWo00oJKMiN/qoAQAaiUAXYAQ79fMGMNgL6CHWLcOvk4MJTZwT+IoAAP3JWzPf2aUqcnQ+J42/Nj7Ato/Fa1hl9TsTH7I6IosGjGFdX2JGoURw6pMWwIr9CAg7Kj/XSROwQIg45uc4AA=="
  },
  "dest-amalfi": {
    "widths": [
      480,
      768,
      1200
    ],
    "ratio": 0.75,
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBQCdASoWAB0APulwrlGpJqQiqAgBIB0JYgCpFVyBnfnW0bhZdLUxLd4QmjTGo9JBGfIAAP6xYliFSV6gEdp6dAPZHJacLwclrJzIHf80bzMoC98DsjjeAhfVe3bVKQWusTckifSbNt3aAFRbQIAA"
  },
  "story-wake": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2000
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAwCdASoWAAwAPulgqU0pJaQiMAgBIB0JQBYdg8NnxPgqpd6fXC8AAP7IOq4FQcU5ssXtbhNaBvI+G6mVqmIn1jPOdscPdpC3HlQetOsAAA=="
  },
  "story-dine": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2000
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAwCdASoWAAwALq10ul0jKSkpCQCsSygFnAIeGAiTtHxqRUMAAP7514UNcYyhQ5+5Jt1gA6rR6nisRvmzghY+8XhhSR0PQroNQAAA"
  },
  "story-ocean": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2000
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoWAAwAPulgqE0pJaQiMAgBIB0JYwC7ACFUw/V8oDAw36QAAP7r8BPlMwkp6r9PPVZnCKgl31atzWm2CGGx3bSwl6LLbgAA"
  },
  "story-return": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2000
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoWAAwAPulep00pJSOiMAgBIB0JZQAASFYayeDFYGMAAP7ZUhOTYvTje7RopqcAbcHBb1z5e/Ec2NSe8POYsoGLiWz0e7gure2g/aHxxSMTdDaHu0tMgAAA"
  },
  "life-dining": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBQCdASoWABYAPulorVApJiQiqAqpIB0JZQDHJvIBnEwNo45UpO7wW+r9A1slXe8BAVSQAProUs1uFRNwPTEAV5evS6Yzf8/ptXMXXzogQUl0bPMuG312Suoj2Jzux8dlM9o5DAu+XBfHwX69BTCSwm7t+IEgdJtLzJSiFZ5Ow8p5IXT0ynxrKxozc3ifkL64y0MEqx3cAAAA"
  },
  "life-spa": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBQCdASoWABYAPulcqU4pJKOiMBgMASAdCWUAxNgPQx11Aj5B9BvjOAzE5q6hyzaAAP5XdM2INwYMf1CkH1f4xBYPX2ONQTKvyd2ULnjbQ5l2ri8AOZwISF6Xo+/F8oTe1SihaQAAAA=="
  },
  "life-pool": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwBACdASoWABYAPuVYp00pJKOiN/VYASAciWgApzTmQONhIDZXFQDwM3FBT+rIoQAA9RcNi3TQWOUc9j5ebo+o52o4zkzHN8m+YZ/YO/C1ss8XdOs0NC2ukN/uKPge9J+TGHnyfph2V3K3617eir56PweKAqf3wAA="
  },
  "life-lounge": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwBACdASoWABYAPt1epE0opaOiMAwBEBuJZQDE2B5LsS/bhTJTPkDjOkDQAAD+8rTOx5UEfthay/V7/hHMUgBXVnZYaZ9c4qvqNeXo2zwoE62CnRcUFL9hS4D6VzX5d+NdEw+YAAA="
  },
  "life-private": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBQCdASoWABYAPulkqk8pJSOiMBgIASAdCWMAuzMOgUVg98pJoT0g+cGaPcG4GktJIMAA/qKqAD+HgSjR/1tDJBe1uULKvXkUmwD7usKXS7cCsMGQCjBwgsHgEo3RE+i3FhyCevkVkNsqcqMARcAAAAA="
  },
  "life-concierge": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQBACdASoWABYAPulqqVCpJaOiqAqpIB0JQBadAaTOETkVP9NAjRFctdXW2gAAvY9yVAjFDqS8ohc9zlmtqLC5cYSQyomY+3QjciXrX6pwPbNIyHC7vzgAKMNCM4IN7Lnh6D2YPAAAAA=="
  },
  "life-wellness": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwBACdASoWABYAPulqqlCpJiOiqAqpIB0JaQAAKdjYUD595p+8BHk1iEVvaxaAAP7xU279pGeksJ5OCl5kI8dN2gBJCQXk6jnUqCcrHcliqaIBjrUHAzNUqYWhwnKOf8ZOmOBGytoAAA=="
  },
  "life-deck": {
    "widths": [
      480,
      768,
      1100
    ],
    "ratio": 1,
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQBACdASoWABYAPuloq1CpJaOiqAqpIB0JZQC06BGmHoUr8JW/mCs6Zki6UOS5AAD+q2bb8K/gcAGzyGVgEJ/AFbJD96YGXUdLDeZc1jAINy847scrskM5wTpZbKigggaum93fZ257MrH5uGxlPUReDuFs3Gdw84AAAA=="
  },
  "interlude-vessel": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2400
    ],
    "ratio": 2.3333,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoWAAkAPuluq08pJyQiMAgBIB0JZwAAUorxUgXfyxKWAAD+6pbmNCe/59raeMkerkr4EdGGMBfnrcQBmcg1Zsw8gAA="
  },
  "service-detail": {
    "widths": [
      480,
      768,
      1200
    ],
    "ratio": 0.8,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBQCdASoWABwAPtlUpE0oJKOiN/qoAQAbCWIAv2svwx0/pXjvOJYL1+Hp2B+1Ihi5WsAA/bzubBgPMw6rx3xqv4EbxcggzNWFVGqwZrFs+f0YsnnXwf3sPnOtWUTGQcC7ki6IfejGITIcch0VZBgt/5r4XExd1UiAQ6DgI+1lYiKf48tdBlvmWWUCsU7dCMWojFfNkgAAAA=="
  },
  "cta-sunset": {
    "widths": [
      480,
      768,
      1200,
      1800,
      2400
    ],
    "ratio": 1.7778,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoWAAwAPulkqE0pJaQiMAgBIB0JYwDCgBIIJ1x4volGDgAA/tC5VJdVNbC4qneeuuicAYndOAcAe24OI7H8hAbEt/4VgAAA"
  }
} as const satisfies Record<string, ImageAsset>;
export type ImageName = keyof typeof IMAGES;
